name: KlockowaCore
version: 1.0
main: me.sajen.klockowacore.Main
api-version: '1.17'
author: Sajen
commands:
  klockowa:
    permission: klockowacore.komendy.klockowa


permissions:
  klockowacore.*:
    default: op
    children:
      klockowacore.komendy.klockowa: true

  klockowacore.komendy.*:
    default: op
    children:
      klockowacore.komendy.klockowa: true

  klockowacore.komendy.klockowa:
    default: not op
